### PR TITLE
Add `web-tooling-benchmark-generator` to the project

### PR DESCRIPTION
**Pull request by alopezsanchez**
[`web-tooling-benchmark-generator`](https://github.com/alopezsanchez/web-tooling-benchmark-generator) is a CLI tool that automates some repetitive task when creating new benchmarks.

### CODE REVIEW

**Comment by alopezsanchez** [comment]
The Node.js 10 jobs failed: https://travis-ci.org/v8/web-tooling-benchmark/jobs/424559097

Maybe we need to update the `package-lock.json`?

**Comment by mathiasbynens** [comment]
Hey @alopezsanchez. `web-tooling-benchmark-generator` looks great — thank you for creating it!

Since it’s a separate project though, I’m a little worried about it getting out of sync with this repository in the future. It also creates additional maintenance burden: if and when we decide to make changes to the benchmark structure, we’d have to either update `web-tooling-benchmark-generator` as well, or remove it from the WTB README. @bmeurer, what do you think?

**Comment by alopezsanchez** [comment]
Hey! No problem. I will maintain it 😃

But yes, I understand your point of view.

**Comment by bmeurer** [comment]
Sounds good to me.

**Comment by mathiasbynens** [comment]
Whoops, we forgot to update `package-lock.json`!

**Comment by alopezsanchez** [comment]
Oops, do you want me to do it?

**Pull request merged**
